# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOEkDVq2_lqW2bAMQ2E-a6rZO4GOPHjk
"""

!pip install transformers datasets pandas scikit-learn torch accelerate -q

import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset

from google.colab import files
uploaded = files.upload()   # select your train.csv file
df = pd.read_csv("train.csv")
print(f"✅ Loaded {len(df)} rows")
print(df.columns.tolist())

df["Category"] = df["Category"].astype(str)
df["Misconception"] = df["Misconception"].fillna("NA").astype(str)
df["label"] = df["Category"] + ":" + df["Misconception"]

unique_labels = sorted(df["label"].unique())
label2id = {l: i for i, l in enumerate(unique_labels)}
id2label = {i: l for l, i in label2id.items()}
print(f"🏷️ Number of unique labels: {len(unique_labels)}")

from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)
print(f"📊 Train: {len(train_df)} rows, Val: {len(val_df)} rows")

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    texts = [f"Question: {q} Answer: {a} Explanation: {e}"
             for q, a, e in zip(examples["QuestionText"], examples["MC_Answer"], examples["StudentExplanation"])]
    return tokenizer(texts, padding="max_length", truncation=True, max_length=256)

train_dataset = Dataset.from_pandas(train_df[["QuestionText", "MC_Answer", "StudentExplanation", "label"]])
val_dataset = Dataset.from_pandas(val_df[["QuestionText", "MC_Answer", "StudentExplanation", "label"]])

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)

# Convert label strings to IDs
train_dataset = train_dataset.map(lambda x: {"label": label2id[x["label"]]})
val_dataset = val_dataset.map(lambda x: {"label": label2id[x["label"]]})

# Set PyTorch format
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(unique_labels),
    id2label=id2label,
    label2id=label2id
)

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,   # adjust to 8 if out of memory
    per_device_eval_batch_size=16,
    num_train_epochs=2,               # 2 is enough for demonstration
    weight_decay=0.01,
    logging_steps=50,
    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

print("🚀 Training started... (this will take 1-2 hours for 36k rows)")
trainer.train()
print("✅ Training finished!")

def predict_top3_all(df, tokenizer, model, id2label, batch_size=32):
    texts = [f"Question: {q} Answer: {a} Explanation: {e}"
             for q, a, e in zip(df["QuestionText"], df["MC_Answer"], df["StudentExplanation"])]
    all_top3 = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        inputs = tokenizer(batch, padding=True, truncation=True, max_length=256, return_tensors="pt")
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        with torch.no_grad():
            outputs = model(**inputs)
            probs = torch.softmax(outputs.logits, dim=-1)
            top3_indices = torch.topk(probs, k=3, dim=-1).indices.cpu().numpy()
        for indices in top3_indices:
            labels = [id2label[idx] for idx in indices]
            all_top3.append(" ".join(labels))
    return all_top3

# Generate predictions for the entire original dataframe
print("🔮 Generating top-3 predictions for all rows...")
top3_list = predict_top3_all(df, tokenizer, model, id2label)

# Create submission CSV
submission = pd.DataFrame({
    "row_id": df["row_id"],
    "Category:Misconception": top3_list
})

# Save and download
submission.to_csv("submission_all_rows.csv", index=False)
from google.colab import files
files.download("submission_all_rows.csv")

print("✅ CSV generated and downloaded!")
print(submission.head(10))